title: ISO/TC 211 Registries
title_html: "ISO/TC&nbsp;211 Registries"
brand_sub: "Geodetic Registry"

theme: jekyll-theme-isotc211

author: "ISO/TC 211"
email: open.source@ribose.com

description: >-
  Registries for geographic information technology
  from ISO/TC 211 Geographic information/Geomatics.

tagline: >-
  Registries for geographic information technology

committee:
  id: 211
  name: Geographic information/Geomatics
  home: https://committee.iso.org/home/tc211

collections:
  pages:
    output: true
    permalink: /:path/

markdown: kramdown

plugins:
  - jekyll/vite
  - jekyll-feed
  - jekyll-data
  - jekyll-asciidoc

nav:
  - title: ISO/TC 211
    url: https://www.isotc211.org

footer_links:
  - title: Main Site
    url: https://www.isotc211.org
  - title: Geodetic Registry
    url: https://geodetic.isotc211.org/
  - title: Schemas
    url: https://schemas.isotc211.org
  - title: Committee Site
    url: https://committee.iso.org/home/tc211

social:
  links:
    - url: https://twitter.com/ISOTC211
    - url: https://github.com/ISO-TC211

powered_by:
  url: https://open.ribose.com
  title: Ribose
  logo_path: /assets/logo-ribose.svg

source: build_source
include:
  - build_source

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - package.json
  - package-lock.json
  - node_modules
  - vendor
  - .sass-cache
  - vite.config.ts
  - postcss.config.js
  - bin
  - _frontend
  - config/vite.json
